// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repositories

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Counterparty struct {
	ID             int32
	IsIndividual   bool
	Unp            pgtype.Int4
	Name           string
	Address        pgtype.Text
	Email          pgtype.Text
	PhoneNumberDgt pgtype.Int8
	ContactName    pgtype.Text
}

type File struct {
	ID  int32
	Url string
}

type Material struct {
	ID   int32
	Name string
}

type Nomenclature struct {
	ID       int32
	GostID   pgtype.Text
	ImageUrl string
}

type Order struct {
	ID               int32
	DateFrom         pgtype.Timestamptz
	DateTill         pgtype.Timestamptz
	ManagerID        int32
	CounterpartiesID int32
	StatusID         int16
	Priority         int16
}

type OrderComment struct {
	ID        int32
	OrderID   int32
	Text      pgtype.Text
	ProfileID int32
}

type OrderItem struct {
	ID             int32
	NomenclatureID int32
	OrderID        int32
	SizeID         int32
	MaterialID     int32
	PlanningCount  int32
	TotalCount     int32
}

type OrderItemsFile struct {
	ID          int32
	FileID      int32
	OrderItemID int32
}

type Profile struct {
	ID         int32
	FirstName  string
	LastName   string
	FatherName pgtype.Text
	Email      string
	PhoneDgt   int64
	Password   string
}

type ProfileRole struct {
	ID        int32
	ProfileID int32
	RoleID    int32
}

type Role struct {
	ID   int16
	Name string
}

type Size struct {
	ID     int32
	Name   string
	Width  int32
	Height int32
}

type Status struct {
	ID   int32
	Name string
}
