// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repositories

import (
	"context"
)

const getProfile = `-- name: GetProfile :one

select id, first_name, last_name, father_name, email, phone_dgt, password from profile where phone_dgt = $2 or email = $1 limit 1
`

type GetProfileParams struct {
	Email    string
	PhoneDgt int64
}

func (q *Queries) GetProfile(ctx context.Context, arg GetProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile, arg.Email, arg.PhoneDgt)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.FatherName,
		&i.Email,
		&i.PhoneDgt,
		&i.Password,
	)
	return i, err
}
